// Copyright (c) 2020-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

// This file is automatically generated. Do not modify it manually.
// We cannot import plugin.json directly because this manifest is generated at build time
// with values injected from the build (e.g. version from git tags, release notes URL).
// See build/manifest/main.go for the generator.

const manifest = JSON.parse(`
{
    "id": "focalboard",
    "name": "Mattermost Boards (PM fork)",
    "description": "Mattermost Boards plugin with project-management extensions: Timeline view, deadlines + DM reminders, dashboard boards, mobile login handoff.",
    "homepage_url": "https://github.com/krotos139/mattermost-plugin-boards-pm",
    "support_url": "https://github.com/krotos139/mattermost-plugin-boards-pm/issues",
    "release_notes_url": "https://github.com/krotos139/mattermost-plugin-boards-pm/releases/tag/v1.2.2",
    "icon_path": "assets/starter-template-icon.svg",
    "version": "1.2.2",
    "min_server_version": "10.7.0",
    "server": {
        "executables": {
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "darwin-arm64": "server/dist/plugin-darwin-arm64",
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "linux-arm64": "server/dist/plugin-linux-arm64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": [
            {
                "key": "EnablePublicSharedBoards",
                "display_name": "Enable Publicly-Shared Boards:",
                "type": "bool",
                "help_text": "This allows board editors to share boards that can be accessed by anyone with the link.",
                "placeholder": "",
                "default": false,
                "hosting": ""
            },
            {
                "key": "EnableMCPServer",
                "display_name": "Enable MCP Server:",
                "type": "bool",
                "help_text": "Run a Model Context Protocol server so AI agents can drive Boards. Users mint personal API keys with the /boards getapi slash command.",
                "placeholder": "",
                "default": false,
                "hosting": ""
            },
            {
                "key": "MCPListenAddress",
                "display_name": "MCP Listen Address:",
                "type": "text",
                "help_text": "host:port for the MCP listener. Default 127.0.0.1:8975 (loopback only). Use 0.0.0.0:\u003cport\u003e to accept connections from outside the host — every TCP request must then carry an API key.",
                "placeholder": "",
                "default": "127.0.0.1:8975",
                "hosting": ""
            },
            {
                "key": "MCPRequireBearerOnLoopback",
                "display_name": "Require API key on loopback:",
                "type": "bool",
                "help_text": "Hardened mode: even local 127.0.0.1 callers must present a Bearer key. Off by default.",
                "placeholder": "",
                "default": false,
                "hosting": ""
            },
            {
                "key": "MCPKeysTable",
                "display_name": "Issued MCP API keys:",
                "type": "custom",
                "help_text": "",
                "placeholder": "",
                "default": null,
                "hosting": ""
            }
        ]
    }
}
`)

export default manifest
export const id = manifest.id
export const version = manifest.version
